# PROOF OF EMPIRE BASE (QWEN)
# Reverse Config (Jordansky)
job: extension
config:
  name: last
  process:
  - type: diffusion_trainer
    training_folder: /app/checkpoints
    device: cuda
    network:
      type: lora
      linear: 32
      linear_alpha: 32

    save:
      dtype: bf16
      save_every: 250
      max_step_saves_to_keep: 4
      save_format: diffusers
    datasets:
    - folder_path: /dataset/images
      caption_ext: txt
      cache_latents_to_disk: true
      resolution: [512, 768, 1024]
      is_reg: false
    train:
      batch_size: 1
      steps: 1600
      lr: 1.0e-4
      optimizer: adamw8bit
      gradient_checkpointing: true
      noise_scheduler: flowmatch
      timestep_type: weighted

      dtype: bf16
      cache_text_embeddings: false
      train_unet: true
      train_text_encoder: false
      ema_config:
        use_ema: true
        ema_decay: 0.999
      caption_dropout_rate: 0.05

      loss_type: huber
      huber_c: 0.1
    model:
      name_or_path: /cache/models
      arch: qwen_image
      quantize: true
      # Local Path Fix for Offline Compatibility
      qtype: float8
      quantize_te: true
      qtype_te: float8
      low_vram: true
meta:
  name: qwen_image_lora_jordansky
  version: '1.6'
